/*
 * This Java source file was generated by the Gradle 'init' task.
 * 
 * side note - in order to run unicode chars use `chcp 65001` in debug
 */
package pizzes;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.Scanner;

import edu.menu.common.interfaces.IOption;
import edu.menu.common.models.Menu;
import edu.menu.common.models.options.StringOption;
import edu.menu.console.ConsoleViewer;

public class App {

    public Menu getMenu() {
        return Menu.builder()
                .setRenderer(new ConsoleViewer())
                .addOption(StringOption.fromStr("Test"))
                .addOption(StringOption.fromStr("Other"))
                .addOption(StringOption.fromStr("אחי היקררררר"))
                .build();
    }

    public static void main(String[] args) throws Exception {
        var app = new App();
        var menu = app.getMenu();

        var res = menu.select();

        if (res.isOk()) {
            System.out.println("Selected options include:");
            for (IOption option : res.unwrap().getOptions()) {
                System.out.println("\t" + option.getDisplayValue());
            }
        } else {
            System.out.println("Sorry we had an error :(");
        }

    }
}
